language: node_js

node_js:
  - "11"
  
addons:
  chrome: stable
  
before_install:
  - google-chrome-stable --headless --disable-gpu
  
install:
  - npm install -g selenium-side-runner
  - npm install -g chromedriver

script:
  - docker run -p 5000:5000 leduclouis/cdp1.5:0.1
  - selenium-side-runner -c "chromeOptions.args=[headless]" testEnv/*.side
