language: node_js

node_js:
  - "11"

install:
  - npm install -g selenium-side-runner
  - npm install -g chromedriver

script:
  - selenium-side-runner -c "chromeOptions.args=[headless]" testEnv/*.side
